'use client';

import React from 'react';
import Link from 'next/link';
import { Sparkles, FileText, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-white">
            <nav className="fixed top-0 left-0 right-0 z-50 bg-black/80 backdrop-blur-xl py-3 border-b border-white/5">
                <div className="max-w-4xl mx-auto px-6 flex items-center justify-between h-12">
                    <Link href="/" className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-lg bg-purple-600 flex items-center justify-center">
                            <Sparkles className="w-4 h-4 text-white" />
                        </div>
                        <span className="text-lg font-display font-bold">PersonaForge</span>
                    </Link>
                    <Link href="/" className="text-sm text-gray-400 hover:text-white flex items-center gap-1">
                        <ArrowLeft className="w-4 h-4" /> Back
                    </Link>
                </div>
            </nav>

            <main className="max-w-3xl mx-auto px-6 pt-32 pb-20">
                <div className="flex items-center gap-3 mb-8">
                    <FileText className="w-8 h-8 text-purple-400" />
                    <h1 className="text-4xl font-display font-bold">Terms of Service</h1>
                </div>
                <p className="text-sm text-gray-500 mb-10">Last updated: March 3, 2026</p>

                <div className="space-y-8 text-gray-300 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By using PersonaForge, you agree to these Terms of Service. If you do not agree, please do not use our services. We reserve the right to update these terms at any time.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">2. Description of Service</h2>
                        <p>PersonaForge provides AI-powered resume building, job description matching, ATS scoring, cover letter generation, and career profile optimization tools. Features vary by subscription tier.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">3. User Accounts</h2>
                        <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 16 years old to use PersonaForge.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">4. Subscriptions & Payments</h2>
                        <p>Paid plans are billed according to the selected pricing tier (weekly or monthly). Payments are processed securely through Razorpay. Refunds are handled on a case-by-case basis within 7 days of purchase.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">5. AI-Generated Content</h2>
                        <p>Content generated by our AI tools is provided as suggestions. You are responsible for reviewing and verifying all generated content before use. PersonaForge does not guarantee employment outcomes based on generated content.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">6. Intellectual Property</h2>
                        <p>You retain ownership of your personal data and resume content. Content you create using PersonaForge is yours. The PersonaForge platform, brand, and technology remain our intellectual property.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">7. Limitation of Liability</h2>
                        <p>PersonaForge is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from the use of our services, including but not limited to employment outcomes or data loss.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-display font-bold text-white mb-3">8. Contact</h2>
                        <p>For questions about these terms, contact us at <span className="text-purple-400">support@personaforge.com</span>.</p>
                    </section>
                </div>
            </main>
        </div>
    );
}
